[package]
name = "ews_xpcom"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.21.3"
ews = { git = "https://github.com/thunderbird/ews-rs.git", rev = "9df4d168969dc2df91bb64d41dafa184ace5630d", version = "0.1.0" }
futures = "0.3.28"
fxhash = "0.2.1"
moz_http = { version = "0.1.0", path = "../moz_http" }
moz_task = { version = "0.1.0", path = "../../../xpcom/rust/moz_task" }
nserror = { version = "0.1.0", path = "../../../xpcom/rust/nserror" }
nsstring = { version = "0.1.0", path = "../../../xpcom/rust/nsstring" }
quick-xml = { version = "0.31.0", features = ["serde"] }
thiserror = "1.0.56"
url = "2.5.0"
xpcom = { version = "0.1.0", path = "../../../xpcom/rust/xpcom" }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
